const mongoose = require('mongoose')
const Schema = mongoose.Schema;
const paymentDetail = new Schema({
    customerId:{
        type:String,
        required:true
    },
    cf_link_id:{
        type:Number,
        required:true
    },
    link_id:{
        type:String,
        required:true
    },
    link_status:{
        type:String,
        required:true
    },
    link_currency:{
        type:String,
        required:true
    },
    link_amount:{
        type:Number,
        required:true
    },
    link_partial_payments:{
        type:Boolean,
        default:false
    },
    link_partial_amount:{
        type:Number,
        default:0
    },
    link_amount_paid:{
        type:Number,
        default:0
    },
    link_minimum_partial_amount:{
        type:Number,
        default:0
    },
    link_purpose:{
        type:String,
        // required:true
    },
    link_created_at:{
        type:String,
        required:true
    },  
    customer_details:{
        customer_name:{
            type:String,
            required:true
        },
        country_code:{
            type:String,
            // required:true
        },
        customer_phone:{
            type:String,
            required:true
        },
        customer_email:{
            type:String,
            required:true
        }
    },
    link_url:{
        type:String,
        required:true
    },
    link_expiry_time:{
        type:String,
        required:true
    },
    order_id:{
        type:String
    },
    link_notify:{
        send_email:{
            type:Boolean,
            default:false
        },
        send_sms:{
            type:Boolean,
            default:false
        }
    }
})
module.exports = mongoose.model ('paymentDetail', paymentDetail)